### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by cryzlasm** [bnbdr/ida-yara-processor#1]
//=================================================================
![image](https://user-images.githubusercontent.com/20424580/51595559-fffadd00-1f31-11e9-930f-d2ec2d05373c.png)

//=================================================================

Warning
---------------------------
Create a segment (00000002-00000000):
 end address is lower than start address.

![image](https://user-images.githubusercontent.com/20424580/51595748-667ffb00-1f32-11e9-9bc8-4790c8138610.png)

//=================================================================
Loading file 'C:\Users\Administrator\Desktop\yararuler' into database...
Detected file format: compiled yara-rule
Loading processor module D:\Program Files\IDA 7.0\procs\yararule_proc.py for yara...OK
Autoanalysis subsystem has been initialized.
  0. Creating a new segment  (00000000-00000002) ... ... OK
     Deleting segment        (00000000-00000002) ...
  0. Creating a new segment  (00000000-036DFF82) ... ... OK
  1. Creating a new segment  (036DFF82-03B94FA7) ... ... OK
added struct "YARA_RULES_FILE_HEADER", id: 4278190144
added struct "YR_RULE", id: 4278190157
added struct "YR_META", id: 4278190172
added struct "YR_NAMESPACE", id: 4278190180
added struct "YR_MATCH", id: 4278190184
added struct "YR_STRING", id: 4278190191
added struct "YR_SIZED_STRING", id: 4278190208
added struct "YR_EXTERNAL_VARIABLE", id: 4278190212
Unloading IDP module D:\Program Files\IDA 7.0\procs\yararule_proc.py...

//=================================================================

RuleFileSize > 50MB

//=================================================================

**Comment by bnbdr** [comment]
Can you upload the file causing this error?

**Comment by cryzlasm** [comment]
I'm sorry I forgot the circumstances
